DROP DATABASE IF EXISTS BnCDB;
CREATE DATABASE BnCDB;

USE BnCDB;

CREATE TABLE BnC(
id INT PRIMARY KEY AUTO_INCREMENT,
answer CHAR(4),
finished BOOLEAN DEFAULT false);

CREATE TABLE Round(
id INT PRIMARY KEY AUTO_INCREMENT,
gameId INT,
guess CHAR(4),
result CHAR(7),
`time` VARCHAR(30));